<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE appconfig [
  <!ELEMENT appconfig (info ,predictPrice ,settings, tiles)>
  <!ELEMENT info (updateDate ,notified ,sysinfo, scheduledTaskError)>
  <!ELEMENT predictPrice (duration ,gasprice ,dieselprice)>
  <!ELEMENT settings (timing , productMonitor ,stationFilters, dailynotify, defaultPage, autoUpdate, soapUpdate, stationBehavior, runPredict)>
  <!ELEMENT scheduledTaskError (#PCDATA)><!-- 背景程式錯誤紀錄，內容是trace -->
  <!ELEMENT tiles (tile*)>
  <!ELEMENT tile EMPTY> <!-- 動態磚 -->
  <!ELEMENT updateDate EMPTY>
  <!ELEMENT priceChange EMPTY>
  <!ELEMENT duration EMPTY>
  <!ELEMENT timing EMPTY>
  <!ELEMENT sysinfo EMPTY><!-- 初次載入和升級資訊 -->
  <!ELEMENT defaultPage EMPTY><!-- 預設頁面 -->
  <!ELEMENT dailynotify (#PCDATA)><!-- 每日預測提醒 -->
  <!ELEMENT autoUpdate EMPTY><!-- 自動更新 -->
  <!ELEMENT soapUpdate EMPTY><!-- 中油SOAP連接 -->
  <!ELEMENT runPredict EMPTY><!-- 執行預測 -->
  <!ELEMENT stationBehavior EMPTY><!-- 點擊加油站行為 -->
  <!ELEMENT stationFilters (FPCC ,CPC ,Self ,Direct ,Favorite ,Kilometer ,Country ,Inservice, Product, Subbrand)>
  <!ELEMENT Subbrand (term*)><!-- 子品牌名稱 -->
  <!ELEMENT term (#PCDATA)><!-- 搜尋關鍵字 -->
  <!ELEMENT productMonitor (product*)><!-- 追蹤油價清單 -->
  <!ELEMENT product EMPTY>
  <!ELEMENT Product EMPTY>
  <!ELEMENT gasprice (#PCDATA)> <!-- 預測汽油價格 -->
  <!ELEMENT dieselprice (#PCDATA)> <!-- 預測柴油價格 -->
  <!ELEMENT FPCC EMPTY><!-- 僅顯示台塑加油站 -->
  <!ELEMENT Self EMPTY><!-- 僅顯示自助加油 -->
  <!ELEMENT CPC EMPTY><!-- 僅顯示中油加油站 -->
  <!ELEMENT Direct EMPTY><!-- 僅顯示直營站 -->
  <!ELEMENT Favorite EMPTY><!-- 僅顯示存檔的加油站 -->
  <!ELEMENT Kilometer (#PCDATA)><!-- 搜尋範圍 -->
  <!ELEMENT notified EMPTY><!-- 背景程式提醒 -->
  <!ELEMENT Country (#PCDATA)><!-- 縣市 -->
  <!ELEMENT Inservice EMPTY><!-- 僅限營業時間 -->
  <!ATTLIST FPCC filter (0 | 1) #REQUIRED>
  <!ATTLIST CPC filter (0|1) #REQUIRED>
  <!ATTLIST Self filter (0 | 1) #REQUIRED>
  <!ATTLIST Direct filter (0 | 1) #REQUIRED>
  <!ATTLIST Favorite filter (0 | 1) #REQUIRED>
  <!ATTLIST Inservice filter (0 | 1) #REQUIRED>
  <!ATTLIST autoUpdate enable (0 | 1) #REQUIRED>
  <!ATTLIST soapUpdate enable (0 | 1) #REQUIRED>
  <!ATTLIST runPredict enable (0|1) #REQUIRED><!-- 載入時執行預測 -->
  <!ATTLIST Country filter (0 | 1) #REQUIRED><!-- 區域過濾 -->
  <!ATTLIST appconfig version CDATA #REQUIRED><!-- 版本 -->
  <!ATTLIST defaultPage page (0|1|2|3) #REQUIRED><!-- 預設頁面，0表示自動，其餘-1 -->
  <!ATTLIST updateDate stationDB  CDATA #REQUIRED> <!-- 加油站資料庫更新時間 -->
  <!ATTLIST updateDate sDBnotifyDate CDATA #REQUIRED><!-- 加油站資料庫更新通知 -->
  <!ATTLIST updateDate DBcheckedDate CDATA #REQUIRED><!-- 資料庫檢查時間 -->
  <!ATTLIST updateDate priceDB CDATA #REQUIRED> <!-- 價格資料庫更新時間 -->
  <!ATTLIST updateDate moeaboeDBdate CDATA #REQUIRED><!-- 能源局油價資料庫 -->
  <!ATTLIST updateDate discountRev CDATA #REQUIRED><!-- 折扣頁面版本 -->
  <!ATTLIST updateDate dDBcheckedDate CDATA #REQUIRED><!-- 折扣資料庫檢查時間 -->
  <!ATTLIST notified CPC (0|1) #REQUIRED> <!-- 背景程式已通知中油更新日期 -->
  <!ATTLIST notified FPCC (0|1) #REQUIRED> <!-- 背景程式已通知台塑更新日期 -->
  <!ATTLIST notified checkHour CDATA #REQUIRED> <!-- 背景程式已通知台塑更新日期 -->
  <!ATTLIST Kilometer lat CDATA #REQUIRED><!-- 搜尋地點 -->
  <!ATTLIST Kilometer long CDATA #REQUIRED><!-- 搜尋地點 -->
  <!ATTLIST Kilometer name CDATA #REQUIRED><!-- 地名 -->
  <!ATTLIST Kilometer filter (0|1) #REQUIRED><!-- 啟動指定位置過濾 -->
  <!ATTLIST Product p92 (0|1) #REQUIRED>
  <!ATTLIST Product p95 (0|1) #REQUIRED>
  <!ATTLIST Product p98 (0|1) #REQUIRED>
  <!ATTLIST Product pdiesel (0|1) #REQUIRED>
  <!ATTLIST Product pgasohol (0|1) #REQUIRED>
  <!ATTLIST dailynotify notified (0|1) #REQUIRED><!-- 本日已提醒 -->
  <!ATTLIST dailynotify checkHour CDATA #REQUIRED><!-- 本日已提醒 -->
  <!ATTLIST dailynotify enable (0|1) #REQUIRED><!-- 啟動本日提醒 -->
  <!ATTLIST duration start CDATA #REQUIRED> <!-- 預測周期開始日 -->
  <!ATTLIST duration end CDATA #REQUIRED> <!-- 預測周期結束日 -->
  <!ATTLIST duration runday CDATA #REQUIRED> <!-- 預測日 -->
  <!ATTLIST timing dailynotifytime CDATA #REQUIRED><!-- 每日提醒時刻 -->
  <!ATTLIST timing updateFreq (0 | 1) #REQUIRED> <!-- 更新時機，每次/周末 -->
  <!ATTLIST timing saveTime (0 | 1) #REQUIRED> <!-- 儲存價格時機，自動/手動 -->
  <!ATTLIST stationBehavior behavior (0|1) #REQUIRED> <!-- 點擊加油站行為，0為單點導航，1為單點看加油站位置 -->
  <!ATTLIST product id (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED> <!-- 追蹤商品清單 -->
  <!ATTLIST tiles default (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | -1) #REQUIRED> <!-- 預設動態磚 -->
  <!ATTLIST tiles updateDate CDATA #REQUIRED><!-- 動態磚更新日期 -->
  <!ATTLIST tile index (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED><!-- 動態磚編號 -->
  <!ATTLIST tile updateDate CDATA #REQUIRED><!-- 動態磚更新時間 -->
  <!ATTLIST sysinfo upgrade (0|1) #REQUIRED><!-- 是否為升級版 -->
  <!ATTLIST sysinfo firstload (0|1) #REQUIRED><!-- 初次使用 -->
  <!ATTLIST predictPrice pause (0|1) #REQUIRED><!-- 啟動預測 -->
  <!ATTLIST scheduledTaskError lasterror CDATA #REQUIRED><!-- 最後一次錯誤 -->
  <!ATTLIST scheduledTaskError timestamp CDATA #REQUIRED><!-- 錯誤發生時間 -->
]>
<appconfig version="636807737900000000">
  <info>
    <updateDate priceDB="0" stationDB="636807737900000000" sDBnotifyDate="636807737900000000" DBcheckedDate="0" moeaboeDBdate="0" discountRev="c9756fca3396f945ad859fc4709ba0ba3380df79" dDBcheckedDate="0"/>
    <notified CPC="0" FPCC="0" checkHour="0"/>
    <sysinfo firstload="0" upgrade="0"/>
    <scheduledTaskError lasterror="0" timestamp="0">0</scheduledTaskError>
  </info>
  <predictPrice pause="0">
    <duration end="0" start="0" runday="0"/>
    <gasprice>0</gasprice>
    <dieselprice>0</dieselprice>
  </predictPrice>
  <settings>
    <timing saveTime="0" updateFreq="0" dailynotifytime="0"/>
    <productMonitor></productMonitor>
    <stationFilters>
      <FPCC filter="0"/>
      <CPC filter="0"/>
      <Self filter="0"/>
      <Direct filter="0"/>
      <Favorite filter="1"/>
      <Kilometer lat="0" long="0" name="" filter="0">3</Kilometer>
      <Country filter="0">0</Country>
      <Inservice filter="1"/>
      <Product p92="0" p95="1" p98="0" pdiesel="0" pgasohol="0"/>
      <Subbrand></Subbrand>
    </stationFilters>
    <dailynotify notified="0" checkHour="0" enable="1">0</dailynotify>
    <defaultPage page="0"/>
    <autoUpdate enable="1"/>
    <soapUpdate enable="1"/>
    <stationBehavior behavior="1"/>
    <runPredict enable="1"/>
  </settings>
  <tiles default="-1" updateDate="0"></tiles>
</appconfig>